Repository ACM-Thapar/CS_COURSE_GUIDE, pull requests merged in 2022-10, with the labels that each got.

#75 added web3 and book resources
  Blockchain/README.md
Labels: hacktoberfest, hacotberfest-accepted

#76 added Web3 folder with all resources
  Blockchain/README.md
  Web3/README.md
Labels: hacktoberfest, hacotberfest-accepted

#78 added Git-Essentials folder with what-is-git.md
  Git-Essentials/what-is-git.md
Labels: hacktoberfest, hacktoberfest-accepted

#79 added install.md and ssh-keys.md and re-organized the project tree is:open label:hacktoberfest-accepted
  Git-Essentials/README.md
  Git-Essentials/assets/contribute.md
  Git-Essentials/assets/git-init.md
  Git-Essentials/assets/install.md
  Git-Essentials/assets/ssh-keys.md
Labels: enhancement, hacktoberfest-accepted

#80 added git-init.md and contribute.md
  Git-Essentials/assets/contribute.md
  Git-Essentials/assets/git-init.md
Labels: hacktoberfest, hacktoberfest-accepted

#81 fixed path to md files, were not loading before
  Git-Essentials/README.md
Labels: bug

#84 Added Networking Courses link
  Bug Bounty/assets/basics.md
Labels: hacktoberfest-accepted

#82 Added Andrew Ng Machine Learning full YouTube course
  Computer-Vision/README.md
Labels: hacktoberfest-accepted

#87 Create commands.md
  Git-Essentials/README.md
  Git-Essentials/assets/commands.md
Labels: hacktoberfest-accepted

#90 new resource added + better readme files
  README.md
  Web-Development/MERN Stack/README.md
Labels: hacktoberfest-accepted
